/**
 * Kanji 感じ - web declarative component framework
 *
 * @author Tan Nhu, tannhu __@__ gmail __.__ com
 * @licence MIT
 * @dependency jsface, jsface.ready, jQuery, JSON || jQuery.parseJSON
 */
(function(h,u,v,w,z,A,x,l){function y(a){return a&&typeof a===u&&!(typeof a.length===v&&!a.propertyIsEnumerable(w))}function q(a){return a&&typeof a===u&&typeof a.length===v&&!a.propertyIsEnumerable(w)}function r(a){return a&&"function"===typeof a}function s(a){return r(a)&&a.prototype&&a===a.prototype.constructor}function t(a,b,d){function m(b,f){d&&d.hasOwnProperty(b)||(a[b]=f,c&&(g[b]=f))}if(q(b))for(var f=b.length;0<=--f;)t(a,b[f],d);else{d=d||{constructor:1,$super:1,prototype:1,$superb:1};var c=
s(a),f=s(b),g=a.prototype,k,n;if(y(b))for(k in b)m(k,b[k]);if(f)for(k in n=b.prototype,n)m(k,n[k]);c&&f&&t(g,b.prototype,d)}}function p(a,b){b||(a=(b=a,0));var d,m,f,c,g,k,n=0,e,h={constructor:1,$singleton:1,$statics:1,prototype:1,$super:1,$superp:1,main:1};g=p.overload;var l=p.plugins;b=("function"===typeof b?b():b)||{};d=b.hasOwnProperty("constructor")?b.constructor:0;m=b.$singleton;f=b.$statics;for(c in l)h[c]=1;d=m?{}:d?g?g("constructor",d):d:function(){};g=m?d:d.prototype;for(k=(a=!a||q(a)?a:
[a])&&a.length;n<k;){e=a[n++];for(c in e)h[c]||(g[c]=e[c],m||(d[c]=e[c]));for(c in e.prototype)h[c]||(g[c]=e.prototype[c])}for(c in b)h[c]||(g[c]=b[c]);for(c in f)d[c]=g[c]=f[c];m||(e=a&&a[0]||a,d.$super=e,d.$superp=e&&e.prototype?e.prototype:e);for(c in l)l[c](d,a,b);r(b.main)&&b.main.call(d,d);return d}p.plugins={};l={Class:p,extend:t,isMap:y,isArray:q,isFunction:r,isString:function(a){return"[object String]"===z.apply(a)},isClass:s};"undefined"!==typeof module&&module.exports?module.exports=l:
(x=h.Class,h.Class=p,h.jsface=l,l.noConflict=function(){h.Class=x})})(this,"object","number","length",Object.prototype.toString);(function(a){a=a.jsface||require("./jsface");var p=a.isFunction,k=[],l=0;a.Class.plugins.$ready=function q(c,b,a,r){for(var f=a.$ready,d=b?b.length:0,m=d,n=d&&b[0].$super,g,e,h;d--;)for(e=0;e<l&&(h=k[e],g=b[d],g===h[0]&&(h[1].call(g,c,b,a),m--),m);e++);n&&q(c,[n],a,!0);!r&&p(f)&&(f.call(c,c,b,a),k.push([c,f]),l++)}})(this);

Class(function(){function l(){var a=q.call(arguments).join(" ");Kanji.notify("log.error",a);console.log("ERROR:",a)}function r(a){a=a&&a.replace(/'/g,'"');try{a=a&&A(a)}catch(c){}return a}function m(a){var c=a.data(n),b=a.data(p),f=h.instanceRefs,e,d;if(c)if(e=h[c]){d=e.componentType;c=r(a.attr(s));switch(d){case "shared":if(!(b=f[b]))a:{var b=h.instanceRefs,g;for(g in b)if(d=b[g],d instanceof e){b={instanceId:g,instance:d};break a}b={instanceId:t++,instance:new e}}e=b;b=e.instanceId;e=f[b]=e.instance;
break;default:b=b||t++,e=f[b]||new e,f[b]=e}e.init(a,c);a.attr(u,b)}else l("Component does not exist [",c,"]");else l("component is not declared on [",a,"]");return f[b]}function v(){k(w).each(function(){var a=k(this);!1===a.data("lazy")&&m(a)})}function x(){var a=h.instanceRefs,c=+new Date,b,f;for(b in a)if(f=k(["[",u,"=",b,"]"].join("")),f.length||delete a[b],+new Date-c>B)break;y(x,z)}var C=window.Touch?"touchend":"click",s="data-cfg",n="com",p="instance",u="data-"+p,w="[data-com]",z=2E3,B=250,
h={instanceRefs:{}},t=1,D=jsface.isFunction,k=jQuery,y=setTimeout,q=[].slice,A="object"===typeof JSON&&JSON.parse||k.parseJSON;return{$statics:{initComponent:m,initAllLazy:v,notify:function(){var a=q.call(arguments),c=a.shift(),b=h.instanceRefs,f,e,d,g;for(f in b)for(g in e=b[f],d=e.listeners,d)if(g===c){d[g].apply(e,a);break}}},init:function(a,c){},listeners:0,$ready:function(a,c,b){this!==a&&((c=b.componentId)?h[c]||(h[c]=a,b.componentType&&(a.componentType=b.componentType)):l("componentId must exist in api",
b))},main:function(a){Kanji=a;k.fn.ready(function(){var a=k(document);v();a.on(C,"button,[role~=button]",function(){var a=k(this),f=a.closest(w),e=f.data(p),d=a.data("act"),g=h.instanceRefs[e],c;c=(d=d&&["on",d.charAt(0).toUpperCase(),d.slice(1)].join(""))&&g&&g[d];if(!e||!g){g=m(f);if(!g)return;c=g&&d&&g[d]}d&&c?D(c)?c.call(g,a,f,r(a.attr(s))):l("action [",d,"] found in component [",f.data(n),"] is not a function"):l("action [",d,"] not found in component [",f.data(n),"]")});a.on("keydown","input",
function(a){});y(x,z)})}}});