(function(h,y,C,z,F,G,A,r,u){function D(a){return a&&typeof a===y&&!(typeof a.length===C&&!a.propertyIsEnumerable(z))&&a||null}function w(a){return a&&typeof a===y&&typeof a.length===C&&!a.propertyIsEnumerable(z)&&a||null}function x(a){return a&&"function"===typeof a&&a||null}function E(a){return x(a)&&a.prototype&&a===a.prototype.constructor&&a||null}function v(a,e,c){if(w(e))for(var B=e.length;0<=--B;)v(a,e[B],c);else{c=c||{constructor:1,$super:1,prototype:1,$superp:1};var B=E(a),h=E(e),b=a.prototype,
p,s;if(D(e))for(p in e){s=p;var n=e[p],l=a,t=B,q=b;c&&c.hasOwnProperty(s)||(l[s]=n,t&&(q[s]=n))}if(h)for(p in s=e.prototype,s){var n=p,l=s[p],t=a,q=B,m=b;c&&c.hasOwnProperty(n)||(t[n]=l,q&&(m[n]=l))}B&&h&&v(b,e.prototype,c)}}function n(a,e){e||(a=(e=a,0));var c,h,A,b,p,s,r=0,l,t={constructor:1,$singleton:1,$statics:1,prototype:1,$super:1,$superp:1,main:1,toString:0};p=n.overload;var q=n.plugins;e=("function"===typeof e?e():e)||{};c=e.hasOwnProperty("constructor")?e.constructor:0;h=e.$singleton;A=
e.$statics;for(b in q)t[b]=1;c=h?{}:c?p?p("constructor",c):c:function(){};p=h?c:c.prototype;for(s=(a=!a||w(a)?a:[a])&&a.length;r<s;){l=a[r++];for(b in l)t[b]||(p[b]=l[b],h||(c[b]=l[b]));for(b in l.prototype)t[b]||(p[b]=l.prototype[b])}for(b in e)t[b]||(p[b]=e[b]);for(b in A)c[b]=p[b]=A[b];h||(l=a&&a[0]||a,c.$super=l,c.$superp=l&&l.prototype?l.prototype:l);for(b in q)q[b](c,a,e);x(e.main)&&e.main.call(c,c);return c}n.plugins={};u={version:G,Class:n,extend:v,mapOrNil:D,arrayOrNil:w,functionOrNil:x,
stringOrNil:function(a){return"[object String]"===F.apply(a)&&a||null},classOrNil:E};"undefined"!==typeof module&&module.exports?module.exports=u:(r=h.Class,h.Class=n,h.jsface=u,u.noConflict=function(){h.Class=r})})(this,"object","number","length",Object.prototype.toString,"2.1.2");
(function(h){h=h.jsface||require("./jsface");var y=h.functionOrNil,C=[],z=0;h.Class.plugins.$ready=function G(h,r,u,D){for(var w=u.$ready,x=r?r.length:0,E=x,v=x&&r[0].$super,n,a,e;x--;)for(a=0;a<z&&(e=C[a],n=r[x],n===e[0]&&(e[1].call(n,h,r,u),E--),E);a++);v&&G(h,[v],u,!0);!D&&y(w)&&(w.call(h,h,r,u),C.push([h,w]),z++)}})(this);
Class(function(){function h(q){for(var a={},f=q&&q.split("|"),k=f&&f.length||0,g,d,c;k--;)if(g=f[k].split(":"),d=g.length,0<d&&3>d)for(1===g.length&&g.unshift(A),d=g[0].split(","),c=d.length;c--;)a[d[c]]=g[1];else console.log(v,"unrecognized action",q);return a}function y(q,a){var f=a?c(q.target):c(this),k=a||q.type,g=z(f),d;d=f.closest(x);var b=d.length&&d.attr(D),b=b&&l.instanceRefs[b];!b&&d.length&&(b=F(d));d=b&&{parent:d,instance:b};if(g&&d&&(b=d.instance,k=g.actions[k])){k=["on",k.charAt(0).toUpperCase(),
k.slice(1)].join("");if(g=b&&e(b[k]))return g.call(b,q,f,d.parent);console.log(v,k,"not yet implemented")}}function C(a){var m,f;for(m in a.actions)if(E[m])a.element.on(m,y);for(f in a.children)C(a.children[f])}function z(a){var m=0,f,k;if(!a||!a.length)return m;if(f=a.attr(r)){f=f.split("/");m=f.shift();f=f.length?f.join(""):null;k=(k=a.attr(u))&&k.replace(/'/g,'"');try{k=k&&b(k)}catch(g){}m={element:a,componentId:m,namespace:f,config:k,actions:h(a.attr(w))};a=a.children(":not([data-com])[data-act]");
if(a=a.length&&a||0){f=a.length;for(k=[];f--;)k.push(z(c(a[f])));m.children=k}}else(f=a.attr(w))&&(m={element:a,actions:h(f)});return m}function F(a){var m=z(a),f=l.instanceRefs,k,g,d,c,b,e,h;if(m)if(k=m.componentId,g=m.instanceId,d=l[k]){c=d.type;k=m.config;switch(c){case "shared":if(!(g=f[g]))a:{g=l.instanceRefs;for(e in g)if(b=g[e],b instanceof d){g={instanceId:e,instance:b};break a}g={instanceId:H++,instance:new d}}b=g;g=b.instanceId;d=f[g]=b.instance;break;default:if(g=g||H++,d=f[g]||new d,f[g]=
d,e=m.namespace,d.namespace=e){c=d.listeners;h={};for(b in c)h[b+"/"+e]=c[b];d.listeners=h}}d.init(a,k);a.attr(D,g);C(m)}else console.log(v,"Component not found",k),Kanji.notify("com:not-found",k,a);return f[g]}function G(){var b=l.instanceRefs,m=+new Date,f,k;for(f in b)if("0"!==f&&(k=c(["[",D,"=",f,"]"].join("")),k.length||delete b[f],+new Date-m>a))break;B(G,n)}var A="click",r="data-com",u="data-cfg",D="data-instance",w="data-act",x="[data-com]",E={mouseenter:1,mouseout:1,mousemove:1,mouseleave:1,
mouseover:1,hover:1},v="[ERROR] Kanji:",n=3E3,a=250,e=jsface.functionOrNil,c=jQuery,B=setTimeout,I=[].slice,b="object"===typeof JSON&&JSON.parse||c.parseJSON,p=0,s=[],H=1,l,t;return{$statics:{notify:function(){var a=I.call(arguments),b=a.shift(),f=l.instanceRefs,c,g,d,b="shared"===this.type?b:this.namespace?[b,"/",this.namespace].join(""):b;for(c in f)g=f[c],d=g.listeners,d[b]&&d[b].apply(g,a);Kanji.debug&&console.log("Kanji:",b)}},init:function(a,b){},listeners:{},$ready:function(a,b,f){var e,g,
d;if(this!==a)if(b=f.id){if(!l[b]){l[b]=a;e=['[data-com="',b,'"][data-lazy="false"],[data-com^="',b,'/"][data-lazy="false"]'].join("");d=a.$superp;for(b=a.$super;d;){d=d.listeners;for(g in d)f.listeners[g]||(f.listeners[g]=d[g]);d=b.$superp;b=b.$super}f.type&&(a.type=f.type);p?c(e).each(function(){F(c(this))}):s.push(e)}}else console.log(v,"componentId not defined on api",f)},main:function(a){Kanji=a;l={instanceRefs:{0:{listeners:{"com:init":F}}}};c.fn.ready(function(){var a=c(document),b=s.length,
e=0,g,d,h;for(p=1;e<b;)if(g=c(s[e++]),d=g.length,h=0,d)for(;h<d;)F(c(g[h++]));a.on("touchend","[data-act]",function(a){t=!0;return y(a,A)}).on(A,"[data-act]",function(a){if(!t)return y(a,A);t=!1});a.on("blur change contextmenu dblclick error focus focusin focusout keydown keypress keyup load mousedown mouseup resize scroll select submit touchcancel touchleave touchmove touchstart unload",function(a){return y(a,a.type)});B(G,n)})}}});